name: geoenv
channels:
  - conda-forge
  - defaults
dependencies:
  - _openmp_mutex=4.5
  - affine=2.4.0
  - attrs=25.3.0
  - blas=1.0
  - blosc=1.21.6
  - branca=0.8.1
  - brotli=1.1.0
  - brotli-bin=1.1.0
  - brotli-python=1.1.0
  - bzip2=1.0.8
  - ca-certificates=2025.4.26
  - cairo=1.18.4
  - certifi=2025.4.26
  - cffi=1.17.1
  - charset-normalizer=3.4.2
  - click=8.2.1
  - click-plugins=1.1.1
  - cligj=0.7.2
  - colorama=0.4.6
  - contourpy=1.3.2
  - cycler=0.12.1
  - descartes=1.1.0
  - double-conversion=3.3.1
  - fiona=1.10.1
  - folium=0.19.7
  - font-ttf-dejavu-sans-mono=2.37
  - font-ttf-inconsolata=3.000
  - font-ttf-source-code-pro=2.038
  - font-ttf-ubuntu=0.83
  - fontconfig=2.15.0
  - fonts-conda-ecosystem=1
  - fonts-conda-forge=1
  - fonttools=4.58.1
  - freetype=2.13.3
  - freexl=2.0.0
  - gdal=3.10.3
  - geopandas=1.1.0
  - geopandas-base=1.1.0
  - geos=3.13.1
  - geotiff=1.7.4
  - graphite2=1.3.13
  - h2=4.2.0
  - harfbuzz=11.2.1
  - hpack=4.1.0
  - hyperframe=6.1.0
  - icc_rt=2022.1.0
  - icu=75.1
  - idna=3.10
  - intel-openmp=2023.1.0
  - jinja2=3.1.6
  - joblib=1.5.1
  - kiwisolver=1.4.7
  - krb5=1.21.3
  - lcms2=2.17
  - lerc=4.0.0
  - libarchive=3.7.7
  - libblas=3.9.0
  - libboost=1.86.0
  - libbrotlicommon=1.1.0
  - libbrotlidec=1.1.0
  - libbrotlienc=1.1.0
  - libcblas=3.9.0
  - libclang13=20.1.6
  - libcurl=8.14.1
  - libdeflate=1.24
  - libexpat=2.7.0
  - libffi=3.4.6
  - libfreetype=2.13.3
  - libfreetype6=2.13.3
  - libgcc=15.1.0
  - libgdal-core=3.10.3
  - libglib=2.84.2
  - libgomp=15.1.0
  - libhwloc=2.11.2
  - libhwy=1.2.0
  - libiconv=1.18
  - libintl=0.22.5
  - libjpeg-turbo=3.1.0
  - libjxl=0.11.1
  - libkml=1.3.0
  - liblapack=3.9.0
  - liblzma=5.8.1
  - libmpdec=4.0.0
  - libpng=1.6.47
  - librttopo=1.1.0
  - libspatialite=5.1.0
  - libsqlite=3.50.0
  - libssh2=1.11.1
  - libtiff=4.7.0
  - libwebp-base=1.5.0
  - libwinpthread=12.0.0.r4.gg4f2fc60ca
  - libxcb=1.17.0
  - libxml2=2.13.8
  - libxslt=1.1.39
  - libzlib=1.3.1
  - lz4-c=1.10.0
  - lzo=2.10
  - mapclassify=2.9.0
  - markupsafe=3.0.2
  - matplotlib=3.10.3
  - matplotlib-base=3.10.3
  - minizip=4.0.10
  - mkl=2023.2.0
  - mkl-service=2.4.0
  - munkres=1.1.4
  - muparser=2.3.5
  - networkx=3.5
  - numpy=2.2.6
  - openjpeg=2.5.3
  - openssl=3.5.0
  - osmium-tool=1.18.0
  - osmnx=2.0.3
  - osmnx-base=2.0.3
  - packaging=25.0
  - pandas=2.3.0
  - pcre2=10.45
  - pillow=11.2.1
  - pip=25.1.1
  - pixman=0.46.0
  - proj=9.6.1
  - pthread-stubs=0.4
  - pycparser=2.22
  - pyogrio=0.11.0
  - pyparsing=3.2.3
  - pyproj=3.7.1
  - pyside6=6.9.1
  - pysocks=1.7.1
  - python=3.13.3
  - python-dateutil=2.9.0.post0
  - python-tzdata=2025.2
  - python_abi=3.13
  - pytz=2025.2
  - qhull=2020.2
  - qt6-main=6.9.1
  - rasterio=1.4.3
  - requests=2.32.3
  - rio-vrt=0.3.1
  - scikit-learn=1.6.1
  - scipy=1.15.3
  - setuptools=80.9.0
  - shapely=2.1.1
  - six=1.17.0
  - snappy=1.2.1
  - snuggs=1.4.7
  - sqlite=3.50.0
  - tbb=2021.13.0
  - threadpoolctl=3.6.0
  - tk=8.6.13
  - tornado=6.5.1
  - tzdata=2025b
  - ucrt=10.0.22621.0
  - uriparser=0.9.8
  - urllib3=2.4.0
  - vc=14.3
  - vc14_runtime=14.42.34438
  - vs2015_runtime=14.42.34438
  - win_inet_pton=1.1.0
  - xerces-c=3.2.5
  - xorg-libxau=1.0.12
  - xorg-libxdmcp=1.1.5
  - xyzservices=2025.4.0
  - zlib=1.3.1
  - zstandard=0.23.0
  - zstd=1.5.7
